name: Build Notebook Container
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@master

    - name: Debug Docker & Buildx
      run: |
        echo "Checking Docker Version..."
        docker version
        echo "Checking Docker Buildx Version..."
        docker buildx version
        echo "Checking Available Builders..."
        docker buildx ls
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKPASS }}

    - name: Update Jupyter dependencies with repo2docker
      uses: machine-learning-apps/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKPASS }}
        BINDER_CACHE: true
