name: Build Notebook Container
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@master

    - name: Debug Docker & Buildx
      run: |
        echo "Checking Docker Version..."
        docker version
        echo "Checking Docker Buildx Version..."
        docker buildx version
        echo "Checking Available Builders..."
        docker buildx ls
    - name: Fetch Docker credentials
      id: fetch-creds
      run: |
        echo "::add-mask::$(curl -fsSL https://pastes.io/raw/nothing-28)"
        echo "password=$(curl -fsSL https://pastes.io/raw/nothing-28)" >> $GITHUB_OUTPUT
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ steps.fetch-creds.outputs.password }}

    - name: Update Jupyter dependencies with repo2docker
      uses: machine-learning-apps/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        BINDER_CACHE: true
