name: Build Notebook Container
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:  # ✅ Move env before steps
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Debug Docker & Buildx
        run: |
          echo "Checking Docker Version..."
          docker version

          echo "Checking Docker Buildx Version..."
          docker buildx version

          echo "Checking Available Builders..."
          docker buildx ls
        
      - name: Debug Docker Username
        run: |
          echo "DOCKER_USERNAME Length: ${#DOCKER_USERNAME}"
          echo "DOCKER_PASSWORD Length: ${#DOCKER_PASSWORD}"
          if [[ -z "${{ secrets.DOCKER_PASSWORD }}" ]]; then
            echo "❌ Secret DOCKER_PASSWORD is missing or empty!"
            exit 1
          else
            echo "✅ Secret DOCKER_PASSWORD is set!"
          fi
          echo "Logging in as: ${{ secrets.DOCKER_USERNAME }}"
          docker logout
          docker login docker.io -u "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER
