name: Sync Fork & Replace Repo
on: 
  workflow_dispatch:  # Manually trigger
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (UTC)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4

      - name: Clone Almond Repository
        run: |
          git clone https://github.com/almond-sh/almond.git almond
          ls -la almond

      - name: Copy Workflows
        run: |
          ls -la
          mkdir -p almond/.github/workflows
          cp .github/workflows/binder.yml almond/.github/workflows/
          cp .github/workflows/sync.yml almond/.github/workflows/
          ls -la almond/.github/workflows/

      - name: Commit & Push Workflows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd almond
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/workflows/binder.yml .github/workflows/sync.yml
          git commit -m "Sync Fork"
          git pull origin main --ff-only
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git main

      - name: Run Binder Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.event.repository.name }}",
              workflow_id: "binder.yml",
              ref: "main"
            });

      - name: Replace Entire Repo with Cloned Almond Repo
        run: |
          rm -rf ./*
          mv almond/* .
          shopt -s dotglob
          mv almond/.* . || true  # Move hidden files
          rm -rf almond  # Cleanup
          ls -la

      - name: Commit & Push Full Repo Replacement
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Replace repository with almond upstream"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git main --force
